config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :wines do
    resources :comments

    collection do
      get :recent
      get :oldest

      get :my_library
    end

    member do
      put "like", to: "wines#upvote"
    end
  end

  root 'wines#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :wine
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wines
  has_many :comments
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  acts_as_votable
  has_attached_file :image, styles: { large: "1000x1000>", medium: "600x600>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :user
  has_many :comments


  scope :recent, ->{ order("created_at DESC") }
  scope :oldest, ->{ order("created_at ASC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_wine
  before_action :authenticate_user!
  before_action :find_comment, only: [:destroy, :edit, :update]
  before_action :comment_owner, only: [:edit, :destroy]

  def create
    @comment = @wine.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to wine_path(@wine)
    else
      render 'new'
    end
  end

  def destroy
    @comment.destroy
    redirect_to wine_path(@wine)
  end

  def edit
  end

  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to wine_path(@wine)
    else
      render 'edit'
    end
  end


  private

  def find_wine
    @wine = Wine.find(params[:wine_id])
  end


  def find_comment
    @comment = @wine.comments.find(params[:id])
  end

  def comment_owner
    unless @comment.user_id == current_user.id
      flash[:notice] = "You shall not pass!"
      redirect_to @wine
    end
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :find_wine, only: [:show, :edit, :update, :destroy, :wine_post_owner, :upvote]
  before_action :authenticate_user!, except: [:index, :show, :recent, :oldest]
  before_action :wine_post_owner, only: [:edit, :update, :destroy]

  def index
    @wines = Wine.all.order("created_at DESC")
  end

  def recent
    @wines = Wine.recent
    render action: :index
  end

  def oldest
    @wines = Wine.oldest
    render action: :index
  end

  def my_library
    if !current_user.nil?
      @wines = current_user.wines
    end
  end

  def show
    @comments = Comment.where(wine_id: @wine).order("created_at DESC")
  end

  def new
    @wine = current_user.wines.build
  end

  def create
    @wine = current_user.wines.build(wine_params)

    if @wine.save
      redirect_to @wine
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @wine.update(wine_params)
      redirect_to @wine
    else
      render 'edit'
    end
  end

  def destroy
    @wine.destroy
    redirect_to root_path
  end

  def upvote
    @wine.upvote_by current_user
    redirect_to :back
  end

  private

  def wine_params
      params.require(:wine).permit(:title, :vintage, :brand, :description, :extracomments, :image, :country, :region, :grape, :rating)
  end

  def find_wine
    @wine = Wine.find(params[:id])
  end

  def wine_post_owner
    unless @wine.user_id == current_user.id
      flash[:notice] = "You shall not pass!"
      redirect_to @wine
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/comments/_comment.html.haml
%h2
  This post has
  = pluralize(@wine.comments.count, "Comment")



- @comments.each do |comment|
  %p
    %b= comment.user.email
  %p= comment.content

  - if comment.user == current_user
    = link_to "Delete", [comment.wine, comment], method: :delete, data: { confirm: " Are you sure?" }
    = link_to "Edit", edit_wine_comment_path(comment.wine, comment)
  %hr



= render 'comments/form'

app/views/comments/_form.html.haml
= form_for([@wine, @wine.comments.build]) do |f|
	= f.text_area :content
	= f.submit

app/views/comments/edit.html.haml
= form_for([@wine, @comment]) do |f|
	= f.text_area :content
	= f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'shared/nav'%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

app/views/shared/_nav.html.haml
%nav
  %ul
    %li
      = link_to "Discover", wines_path

    - if user_signed_in?
      %li
        = link_to "New wine", new_wine_path
      %li
        = link_to "My library", my_library_wines_path
      %li
        = link_to "Edit profile", edit_user_registration_path
      %li
        = link_to "Sign out", destroy_user_session_path, method: :delete
    - else
      %li
        = link_to "Sign in", new_user_session_path
      %li
        = link_to "Sign up", new_user_registration_path

app/views/wines/_form.html.haml
.card
  = form_for @wine, url: wines_path, html: { multipart: true } do |wine|

    .field
      = wine.file_field :image

    .field
      = wine.text_field :title, placeholder: "Name of the wine"

    .field
      = wine.text_field :brand, placeholder: "The brand of the wine"

    .field
      = wine.text_field :country, placeholder: "Which country is the wine from"

    .field
      = wine.text_field :region, placeholder: "Which region in that country?"

    .field
      = wine.text_area :grape, placeholder: "Which grapes were used?"

    .field
      = wine.date_select :vintage, { discard_day: true, discard_month: true, start_year: 1600, end_year: Time.now.year + 1}

    .field
      = wine.text_area :description, placeholder: "How would you describe it? fx smells, taste etc"

    .field
      = wine.text_area :extracomments, placeholder: "Comments/Thoughts, what did you think, what would this wine go well with? fx steak"

    .field
      = wine.text_field :rating, placeholder: "RATING 1-5"

    .field
      = wine.submit

app/views/wines/edit.html.haml
.card
  %h1 Edit post
  = form_for @wine, html: { multipart: true } do |wine|

    .field
      = wine.file_field :image

    .field
      = wine.text_field :title, placeholder: "Name of the wine"

    .field
      = wine.text_field :brand, placeholder: "The brand of the wine"

    .field
      = wine.text_field :country, placeholder: "Which country is the wine from"

    .field
      = wine.text_field :region, placeholder: "Which region in that country?"

    .field
      = wine.text_area :grape, placeholder: "Which grapes were used?"

    .field
      = wine.label :vintage
      = wine.date_select :vintage, { discard_day: true, discard_month: true, start_year: 1600, end_year: Time.now.year + 1}

    .field
      = wine.text_area :description, placeholder: "How would you describe it? fx smells, taste etc"

    .field
      = wine.text_area :extracomments, placeholder: "Comments/Thoughts, what did you think, what would this wine go well with? fx steak"

    .field
      -# = wine.text_field :rating, placeholder: "RATING 1-5"
      #user_stars

    .field
      = wine.submit


:javascript
  $('#user_stars').raty({
    path: '/assets',
    scoreName: 'wine[rating]',
    score: 1
  });

app/views/wines/index.html.haml
- content_for :title, "Winelog.xyz | Discover"

.ordering
  %ul
    %li
      = link_to "Recent", recent_wines_path
    %li
      %a{:href => "/"} Popular
    %li
      = link_to "Oldest", oldest_wines_path
    %li
      %a{:href => "/"}
      = icon('search')

  %hr

.all_wines.transitions-enabled
  - @wines.each do |wine|
    .specific_wine
      .numse
        = image_tag wine.image.url(:medium)
      .wine_info
        %h1= link_to wine.title, wine
        %hr
        %p
          %b Description:
          = truncate(wine.description, length: 200)
        .rating{:id => "stars_#{wine.id}"}
        %br

        :javascript
            $('#stars_#{wine.id}').raty({
              path: '/assets',
              readOnly: true,
              score: #{wine.rating}
            });

app/views/wines/my_library.html.haml
- content_for :title, "Winelog.xyz | My library"
%h1 My library

.ordering
  %ul
    %li
      = link_to "Recent", recent_wines_path
    %li
      %a{:href => "/"} Popular
    %li
      = link_to "Oldest", oldest_wines_path
    %li
      %a{:href => "/"}
      = icon('search')

  %hr

.all_wines.transitions-enabled
  - @wines.each do |wine|
    .specific_wine
      .numse
        = image_tag wine.image.url(:medium)
      .wine_info
        %h1= link_to wine.title, wine
        %hr
        %p
          %b Description:
          = wine.description

app/views/wines/new.html.haml
.card
  %h1 New post
  = form_for @wine, url: wines_path, html: { multipart: true } do |wine|

    .field
      = wine.file_field :image

    .field
      = wine.text_field :title, placeholder: "Name of the wine"

    .field
      = wine.text_field :brand, placeholder: "The brand of the wine"

    .field
      = wine.text_field :country, placeholder: "Which country is the wine from"

    .field
      = wine.text_field :region, placeholder: "Which region in that country?"

    .field
      = wine.text_area :grape, placeholder: "Which grapes were used?"

    .field
      = wine.label :vintage
      = wine.date_select :vintage, { discard_day: true, discard_month: true, start_year: 1600, end_year: Time.now.year + 1}

    .field
      = wine.text_area :description, placeholder: "How would you describe it? fx smells, taste etc"

    .field
      = wine.text_area :extracomments, placeholder: "Comments/Thoughts, what did you think, what would this wine go well with? fx steak"

    .field
      -# = wine.text_field :rating, placeholder: "RATING 1-5"
      #user_stars

    .field
      = wine.submit


:javascript
  $('#user_stars').raty({
    path: '/assets',
    scoreName: 'wine[rating]',
    score: 1
  });

app/views/wines/show.html.haml
.card-show
  .centered-items
    = image_tag @wine.image.url(:medium)
    %h1= @wine.title
    .item{:id => "stars_#{@wine.id}"}
    - if current_user == @wine.user
      = link_to "Edit", edit_wine_path(@wine)
      = link_to "Delete", wine_path(@wine), method: :delete, data: { confirm: "Are you sure?" }

  .wine-info-show
  %p
    %b Vintage:
    = @wine.vintage.year
  %p
    %b Country:
    = @wine.country
  %p
    %b Region:
    = @wine.region
  %p
    %b Grapes:
    = @wine.grape
  %p
    %b Description:
    = @wine.description
  %p
    %b Extra comments:
    = @wine.extracomments
  %p
    %b Created by:
    = @wine.user.email


  = link_to like_wine_path(@wine), method: :put do
    = icon('thumbs-up')
    = @wine.get_upvotes.size

  = render 'comments/comment'


:javascript
    $('#stars_#{@wine.id}').raty({
      path: '/assets',
      readOnly: true,
      score: #{@wine.rating}
    });